spring:
  main:
    banner-mode: console
  application:
    name: xconfig
  # redis config
  redis:
    host: localhost
    database: 0           # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100ms
    port: 6379
    password:             # Redis服务器连接密码（默认为空）


thread:
  pool:
    corePoolSize: 3
    maxPoolSize: 5
    queueCapacity: 20
    keepAliveSeconds: 30
    allowCoreThreadTimeOut: true
    threadNamePrefix: custom-thread-
    waitForTasksToCompleteOnShutdown: true
    rejectedExecutionHandler: AbortPolicy